### ISSUE TITLE
Removes codes

### ISSUE THREAD

**Issue by thelegendclub** [Syralist/esphomekeypad#3]
Can It removes function codes after use (after a few seconds) automatically?

**Comment by Syralist** [comment]
I don't know if I understood you correctly, but now the textsensor sends an empty string 300 cycles after the last keypress. On my nodeMCU that amounts to about 4 seconds.

**Comment by thelegendclub** [comment]
> No sé si te entendí correctamente, pero ahora el sensor de texto envía una cadena vacía 300 ciclos después de la última pulsación de tecla. En mi nodeMCU eso equivale a unos 4 segundos.

Yes that's what I mean.  But does it have to be set or does it automatically?  Because in my case it is not like that.

**Comment by Syralist** [comment]
I added the feature just now. It now does that automatically.

**Comment by thelegendclub** [comment]
> Agregué la función justo ahora. Ahora lo hace automáticamente.

Thank you.  I download it and check it.

**Comment by thelegendclub** [comment]
> Agregué la función justo ahora. Ahora lo hace automáticamente.
It doesn't compile me. It gives me these errors.



In file included from src/main.cpp:64:0:
src/keypad_textsensor.h: In member function 'virtual void KeypadTextSensor::loop()':
src/keypad_textsensor.h:42:17: error: 'keyPressed' was not declared in this scope
                 keyPressed = true;
                 ^
src/keypad_textsensor.h:45:13: error: 'keyPressed' was not declared in this scope
         if (keyPressed){
             ^
src/keypad_textsensor.h:46:13: error: 'resetCounter' was not declared in this scope
             resetCounter++;
             ^
src/keypad_textsensor.h:48:13: error: 'resetCounter' was not declared in this scope
         if (resetCounter >= resetTime){
             ^
src/keypad_textsensor.h:48:29: error: 'resetTime' was not declared in this scope
         if (resetCounter >= resetTime){
                             ^
src/keypad_textsensor.h:52:13: error: 'keyPressed' was not declared in this scope
             keyPressed = false;
             ^
*** [/data/alarma_entrada/.pioenvs/alarma_entrada/src/main.cpp.o] Error 1
========================= [FAILED] Took 10.93 seconds =========================
