### ISSUE TITLE
I don't know how to make this to work

### ISSUE THREAD

**Issue by Mavi222** [Syralist/esphomekeypad#4]
Hey,

I am a complete noob. I just got the 4x3 and 4x4 keypads, and I would like to implement the 4x3 keypad in the home assistant. I have no idea what to do with these files, can you please write me a little step by step instructions of how to make this work? 

Thanks a lot in advance,

Mavi

**Comment by paki111** [comment]
You have to read about ESPHome Add-on
https://esphome.io/guides/getting_started_hassio.html

When you have established connection with your ESP board in ESPHome, you can edit and upload *.yaml file.
Additional step here is to add custom library (*.h file) to source files.
