### ISSUE TITLE
Wrong "A" and "B" in KeyPad 4x4

### ISSUE THREAD

**Issue by tymzang** [Syralist/esphomekeypad#5]
When I am using KeyPad 4x4, I always get wrong "A" and "B", other keys are correct. Specially, "A" become "1" and "B" become "4". I think my KeyPad is defected, but I tried with Arduino Mega/Uno, these keys are correct. I think there is problem with your files or library in ESPHome? Looking forward to any help. Many thanks.

**Comment by Syralist** [comment]
I never tested this with a 4x4 keypad. I only have a 3x4. I think you need to adjust the `keys` array and the `n_cols` in the keypad_sensor.h file.

**Comment by tymzang** [comment]
Yes, I did. But I wonder why C and D are perfect, only A and B are wrong. I think something wrong with matrix location of [1,4] and [2,4] in the library.

    static const byte n_rows = 4;
    static const byte n_cols = 4;

    static const unsigned int resetTime = 300;
    unsigned int resetCounter = 0;
    bool keyPressed = false;
    
    char keys[n_rows][n_cols] = {
    {'1','2','3','A'},
    {'4','5','6','B'},
    {'7','8','9','C'},
    {'*','0','#','D'}
    };
    
    byte rowPins[n_rows] = {D1, D2, D3, D4};
    byte colPins[n_cols] = {D5, D6, D7, D8};

**Comment by Syralist** [comment]
Have a look at this fork: https://github.com/paki111/esphomekeypad_4x4
He seems to have a 4x4 working.

**Comment by tymzang** [comment]
Thanks @Syralist ... but his "keypad_4x4.h" is wrong with variable name. After fixing variable name, his code or your code are the same. I believed there is something wrong with Keypad library since it will be downloaded to HA during code compiling. There are a lot of Keypad libraries in ESPhome, then ESPhome just use first Keypad library in the list. It means we can not control the external library. In Arduino environment, my code and Keypad board works extremely well. I think my best solution is stop investigating the library, buy Keypad 3x4 and solve my problem.

**Comment by olddawgpowers** [comment]
Using D8 did not work for me.  My 4x4 keypad works correctly using the following.
    static const byte n_rows = 4;
    static const byte n_cols = 4;
    
	char keys[n_rows][n_cols] = {
	 {'1','2','3','A'},
	 {'4','5','6','B'},
	 {'7','8','9','C'},
	 {'*','0','#','D'}
	};
	 
	byte colPins[n_rows] = {D3, D2, D1, D0};
	byte rowPins[n_cols] = {D7, D6, D5, D4};
