### ISSUE TITLE
Keypad press

### ISSUE THREAD

**Issue by olddawgpowers** [Syralist/esphomekeypad#6]
Not an issue, but I am not sure where to put a request?  I would like to detect when the keypad is pressed so I can make an audible sound?  I am using the keypad_textsensor.h and keypadtext.yaml.   Is there a way to do that with existing code in yaml?

**Comment by Syralist** [comment]
With the existing code that is not possible. I will think about it, maybe I can come up with a solution.

**Comment by olddawgpowers** [comment]
Thank you- I think I figured it out.  I added the following after  if (myKey != NO_KEY){
			//added for passive buzzer
			for (int i = 0; i <15; i++) 
			{
			  digitalWrite (10, HIGH) ;
			  delay (1) ;// delay 1ms
			  digitalWrite (10, LOW) ;
			  delay (1) ;// delay 1ms
			}
