### ISSUE TITLE
timeout issues

### ISSUE THREAD

**Issue by callacomp** [Syralist/esphomekeypad#7]
Hi
Fantastic to find your code, as I need a small 3x4 keypad for my HomeAssistant Alarm panel.
Whilst testing it I noticed some strange things happening but as I'm no programmer didn't quite know where to look, but I figured the logic must be in the keypad_textsensor.h file. After adding in some extra publish_states I noticed that the timeout of 300 kept on going even if you reset it with * or entered a code with #. If the code was wrong first time but within say 200ms you then only had 100ms before it times out and when I pressed # I only had the last character or so. I've changed you code very slightly and put some comments in. Do you think they need adding or updating to your code, or even add a new variant?

`    void setup() override {
    // This will be called by App.setup()
    }
    void loop() override {
    // This will be called by App.loop()
        char myKey = myKeypad.getKey();
        if (myKey != NO_KEY){
            if (myKey == '#'){
                publish_state(keysequenz);
                keysequenz.clear();
                // Nigels code
                // publish_state("send keyboard buffer and reset counter");
                // reset counter until next key is pressed
                resetCounter = 0;
                // reset key pressed until next key is pressed
                //also stops if keyPredded below
                keyPressed = false;
            }
            else if (myKey == '*'){
                keysequenz.clear();
                publish_state(keysequenz);
                // Nigels code
                // publish_state("reset keyboard buffer and counter");
                // Nigels code
                // reset key pressed until next key is pressed
                resetCounter = 0;
                // reset key pressed until next key is pressed
                //also stops if (keyPressed) below and its counter
                keyPressed = false;
            }
            else {
                keysequenz.push_back(myKey);
                keyPressed = true;
            }
        }
        if (keyPressed){
            resetCounter++;
            // Nigels code
            // publish_state("A key pressed increase counter");
        }
        if (resetCounter >= resetTime){
            // publish_state("couter greater than 300");
            // publish timeout so HomeAssistant can handle it
            publish_state("timeout");
            keysequenz.clear();
            // published a blank code as its been cleared
            // removed next line which is a blank code
            //publish_state(keysequenz);
            resetCounter = 0;
            keyPressed = false;
        }
    }
};`

**Comment by Syralist** [comment]
Hi,
your solution is good, I added it to the code. Thanks for the contribution! :)
