### ISSUE TITLE
Can the sensor reset the status?

### ISSUE THREAD

**Issue by fbarberis** [Syralist/esphomekeypad#8]
Hi, first of all I want to thank you for your code. I was able to adapt it for a 4x4 keypad with no problems and I learned a lot in the process.
I use this keypad as a shortcut on my desktop to control devices and launch scripts.  In Home Assistant, to use it as a trigger for an automation, I use the sensor state (**To: 1**, for example), this is a problem when I want to use it as a toggle for a light, for example, because if I want to turn it on and off I have to press **1**, press another key to make the sensor state something **other than 1** and press **1** again. A possible solution would be to have the sensor automatically reset its value after 1 second, for example. Could you guide me in some direction to achieve this? I am not a programmer, but I can defend myself by researching.

**Comment by Syralist** [comment]
Hi, the KeypadTextSensor does something similar. Whenever a key is pressed I increase a counter variable in every cycle. Then after a certain amount of cycles it resets the keysequence. Maybe you can adapt that.
If I find the time I will try and make a version that does what you suggest.

**Comment by Syralist** [comment]
I uploaded a new version that automatically resets the value. ;)

**Comment by fbarberis** [comment]
It works perfectly! Thank you so much, you are amazing!
