### ISSUE TITLE
How do I activate the internal Pull up or Pull down resistor inside the *.h file?

### ISSUE THREAD

**Issue by master4g** [Syralist/esphomekeypad#9]
Hey, I'm using an extension cable between the esp and the matrix keypad and I'm having a floating problem and the wire is picking up all sort of noise. I'm told I need a Pull Up or Pull Down resistor which I can solder on physically, or use the internal one by putting it in the code. On line 23 and 24 of the *.h file, where the pins are defined, how do I also tell esphome to use the built in Pull down resistor? Thanks

**Comment by Syralist** [comment]
Hi, you actually can't change the pinmodes yourself. The Keypad library does pinmode switching between input and output to read the key matrix.
Have a look at https://esphome.io/components/sx1509.html . Maybe you can get around your noise problem with this.
